Add a behat-testing job using machine executor
ramsalt/circleci-orb pull request #10
Opened 2023-03-03 08:49 UTC by jfauske

2023-03-03 13:25 UTC, jfauske commented
A poc project exists here: https://bitbucket.org/ramsalt/behat-poc-composer/
With circleci testing here: https://app.circleci.com/pipelines/bitbucket/ramsalt/behat-poc-composer?branch=develop

2023-03-06 09:01 UTC, jfauske commented
As we can NOT share the docker "environment" between jobs, I wonder if it would make sense to extend this job to include other tests that may require a full site setup before running various tests.( i.e unit-tests etc.)
We could add parameters to control which testsuites to run on each project.

Or would it make more sense to make the "site setup" a command that we can use with multiple testsuite jobs?

Codesniffer and any static analysis tools should be easy to run in individual jobs just using the stock circleci php image...

Thoughts or comments @szeidler?

2023-03-07 12:50 UTC, szeidler commented
Yes, static code analysis tools like code sniffer, drupal-check can easily use the default CircleCI base images. Actually also Unit tests, because PHP is the only dependency for them.

**Kernel tests**
Requires PHP and database. Drupal installs a separate database (or tables) for running the tests.

**Functional tests**
Requires PHP and database. Drupal installs a separate database (or tables) for running the tests.

**Functional Javascript tests and Behat Tests**
Requires PHP, database and a browser driver like Selenium and/or Chromedriver. Drupal installs a separate database (or tables) for running the tests.

**Existing Site Tests**
This is a special kind of test provided by https://gitlab.com/weitzman/drupal-test-traits . It runs tests from an existing site, so basically like the local environment.

2023-03-07 12:53 UTC, szeidler commented
In general I agree with you. Where we cannot use `persist_to_workspace` to make files available across different workflows/jobs we should use parameters (even steps are a parameter type) to influence which tests to run.
For Drupal tests (Unit, Kernel, Functional, Functional Javascript) we might not even need the parameters. We can try to run them all step by step and they should just succeed/skip when no matching tests have been found.

2023-03-08 08:43 UTC, jfauske commented
Thanks for the input.
Then I think renaming this job to i.e `drupal-tests` and add any test framework that require a Drupal database here.
For any framework that require only php, we can continue to call those i.e `php-<testsuite>` like we did with the `php-codesniffer` job?

We also need make some quickstart-configuration files available for all test frameworks we decide to use.
Should we rename this repo https://bitbucket.org/ramsalt/common-behat-tests/src/main/ and add all "scaffolding" and config examples there? 
Or would it be better to split that into framework-specific composer packages?

2023-03-08 10:55 UTC, jfauske commented
@mnlund Please feel free to pitch in with comments here as well.

2023-03-12 10:57 UTC, szeidler requested changes

2023-03-12 10:57 UTC, szeidler commented on src/jobs/drupal-behat-tests.yml
> +            echo "No 'settings.ramsalt.circleci-tests.php.example' found - bailing out!"
@jfauske I think something is odd with the file existence check and the error message. The error message seems to be misleading.

I think we have a problem with the order of steps here. The `settings.ramsalt.local.php.example` comes from `ramsalt/drupal-scaffold`, but is gitignored and is therefore dependent on composer install and drupal-scaffold running before.

2023-03-12 10:57 UTC, szeidler commented on src/commands/get-wodby-instance-uuid.yml
> +  wodby-application-uuid:
@jfauske Should we use an underscore here. I already see some inconsistencies but it seems for command parameters we mainly use underscores instead of dashes.

We should have a closer look and make it as consistent as possible, but trying to be backwards compatible, because we cannot easily change all project configurations.

2023-03-12 10:57 UTC, szeidler commented on src/jobs/drupal-behat-tests.yml
> +        docker exec -w /var/www/html -u wodby php vendor/bin/behat --profile circleci
@jfauske We should store junit test artifacts.

2023-03-12 11:43 UTC, jfauske commented on src/jobs/drupal-behat-tests.yml
> +            echo "No 'settings.ramsalt.circleci-tests.php.example' found - bailing out!"
Yes, I forgot to change that message here when I started working on the `drupal-tests` job.
I initially started out with a `settings.ramsalt.circleci-tests.php` "scaffolded" from the `common-behat-tests` repo.
But it was essentially just doing the same as the `local` settings did, so I decided to loose the new one in later iterations.

2023-03-12 11:47 UTC, jfauske commented on src/commands/get-wodby-instance-uuid.yml
> +  wodby-application-uuid:
Ideally yes, we should be consistent all over.
We use hyphens in https://github.com/ramsalt/drupal-scaffold/blob/master/assets/circleci.config.yml
But underscores in https://github.com/ramsalt/circleci-orb/blob/master/src/jobs/build-drupal-and-deploy-on-wodby.yml
Will fix it so that we use underscores consistently in the orb jobs and acommands.

2023-03-12 11:47 UTC, jfauske commented on src/jobs/drupal-behat-tests.yml
> +        docker exec -w /var/www/html -u wodby php vendor/bin/behat --profile circleci
Yes, it's done in the `drupal-tests` job, which is supposed to "supersede" this job.

2023-03-12 11:57 UTC, jfauske commented on src/commands/get-wodby-instance-uuid.yml
> +  wodby-application-uuid:
For the files added by this PR, fixed in fea1060

2023-03-12 11:59 UTC, jfauske commented on src/jobs/drupal-behat-tests.yml
> +            echo "No 'settings.ramsalt.circleci-tests.php.example' found - bailing out!"
I've made the output reflect actual filename test in a94ae0a.
Now we can discuss what filename to actually use across packages/features.

2023-03-12 12:01 UTC, jfauske commented on src/jobs/drupal-behat-tests.yml
> +        docker exec -w /var/www/html -u wodby php vendor/bin/behat --profile circleci
Fixed in e62a079

2023-03-12 14:28 UTC, szeidler commented on src/jobs/drupal-behat-tests.yml
> +            echo "No 'settings.ramsalt.circleci-tests.php.example' found - bailing out!"
Thanks. But I think the second part of my comment still remains. With a out-of-the-box installation of a ramsalt project with ramsalt/drupal-scaffold the file does not exist, before `composer install` has been run.

2023-03-12 15:21 UTC, szeidler commented
@jfauske Have you tried running functional tests? I run into a "Permission denied" It seems to be related to the `BROWSERTEST_OUTPUT_DIRECTORY` environment variable in phpunit.xml and the defined directory in combination with the wodby user to run the tests. We need to look into it for the out-of-the-box experience.

2023-03-12 16:08 UTC, jfauske commented on src/jobs/drupal-behat-tests.yml
> +            echo "No 'settings.ramsalt.circleci-tests.php.example' found - bailing out!"
Yes, that's what I was trying to address with my "now we can discuss...".
With 7820ba6 I've made the test env "name" configurable, and thus also the name of the file we are looking for.
It will default to `tests`. So we could add that as an asset to the `common-behat-tests` package, and create it if it doesn't exist.

2023-03-12 16:24 UTC, jfauske commented
@szeidler I only ran functional tests locally this far, with phpunit.xml.dist copied from `web/core` modified to match that config.
Before committing that to any scaffolding package, we need some modifications and maybe some "boilerplate" of our own.
That's something I'd like to discuss.
Running all the tests that come with Drupal takes hours and I'm not sure spending our CI minutes on that is much value for money.

2023-03-12 17:28 UTC, szeidler commented
@jfauske yes, I would vote for an own boilerplate. I have at least one good example for it. Of course, we don't need to run Drupal Core tests. What is already test covered by a dependency we don't need to test ourselves.

2023-03-22 13:05 UTC, szeidler approved these changes

2023-03-22 13:06 UTC, merged